export const bairros = [
    "Água Verde",
    "Amizade",
    "Baependi",
    "Barra do Rio Cerro",
    "Barra Do Rio Cerro",
    "Barra do Rio Molha",
    "Barra Do Rio Molha",
    "Braço Do Ribeirão Cavalo",
    "Braço Ribeirão Cavalo",
    "Centenário",
    "Centro",
    "Chico de Paulo",
    "Chico De Paulo",
    "Czerniewicz",
    "Estrada Nova",
    "Garibaldi",
    "Ilha da Figueira",
    "Ilha Da Figueira",
    "Jaraguá 84",
    "Jaraguá 99",
    "Jaragua Esquerdo",
    "Jaraguá Esquerdo",
    "Jaraguazinho",
    "João Pessoa",
    "Nereu Ramos",
    "Nova Brasilia",
    "Nova Brasília",
    "Parque Malwee",
    "Pedra De Amolar",
    "Rau",
    "Ribeirão Cavalo",
    "Ribeirão Grande Do Norte",
    "Rio Cerro I",
    "Rio Cerro Ii",
    "Rio da Luz",
    "Rio Da Luz",
    "Rio Molha",
    "Santa Luzia",
    "Santo Antônio",
    "São Luis",
    "São Luís",
    "Tifa Martins",
    "Tifa Monos",
    "Tifa Schubert",
    "Tres Rios Do Norte",
    "Três Rios do Norte",
    "Três Rios Do Norte",
    "Tres Rios Do Sul",
    "Três Rios do Sul",
    "Três Rios Do Sul",
    "Vieira",
    "Vieiras",
    "Vila Baependi",
    "Vila Chartres",
    "Vila Lalau",
    "Vila Lenzi",
    "Vila Nova"
] as const
