org: germanyn
app: mobihub
service: mobihub

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  profile: mobihub
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "lambda:InvokeFunction"
          Resource: "*"

useDotenv: true

package:
  individually: true

functions:
  itaivan-dispatcher:
    handler: src/itaivan/itaivan-dispatcher.handler
  itaivan-crawler:
    handler: src/itaivan/itaivan-crawler.handler
  vivenda-dispatcher:
    handler: src/vivenda/dispatcher.handler
  vivenda-crawler:
    handler: src/vivenda/crawler.handler
plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    packager: 'yarn'
  serverless-offline:
    httpPort: 3674
    lambdaPort: 3675
